#ifndef QTCCREATOR3_GLOBAL_H
#define QTCCREATOR3_GLOBAL_H

#if defined(QTCCREATOR3_LIBRARY)
#  define QTCCREATOR3_EXPORT Q_DECL_EXPORT
#else
#  define QTCCREATOR3_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCCREATOR3_GLOBAL_H
