# CMake generated Testfile for 
# Source directory: /home/josh/llama.cpp-master/tests
# Build directory: /home/josh/llama.cpp-master/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-tokenizer-0-bert-bge "/home/josh/llama.cpp-master/bin/test-tokenizer-0" "/home/josh/llama.cpp-master/models/ggml-vocab-bert-bge.gguf")
set_tests_properties(test-tokenizer-0-bert-bge PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;38;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;118;llama_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-command-r "/home/josh/llama.cpp-master/bin/test-tokenizer-0" "/home/josh/llama.cpp-master/models/ggml-vocab-command-r.gguf")
set_tests_properties(test-tokenizer-0-command-r PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;38;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;119;llama_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-deepseek-coder "/home/josh/llama.cpp-master/bin/test-tokenizer-0" "/home/josh/llama.cpp-master/models/ggml-vocab-deepseek-coder.gguf")
set_tests_properties(test-tokenizer-0-deepseek-coder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;38;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;120;llama_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-deepseek-llm "/home/josh/llama.cpp-master/bin/test-tokenizer-0" "/home/josh/llama.cpp-master/models/ggml-vocab-deepseek-llm.gguf")
set_tests_properties(test-tokenizer-0-deepseek-llm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;38;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;121;llama_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-falcon "/home/josh/llama.cpp-master/bin/test-tokenizer-0" "/home/josh/llama.cpp-master/models/ggml-vocab-falcon.gguf")
set_tests_properties(test-tokenizer-0-falcon PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;38;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;122;llama_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-gpt-2 "/home/josh/llama.cpp-master/bin/test-tokenizer-0" "/home/josh/llama.cpp-master/models/ggml-vocab-gpt-2.gguf")
set_tests_properties(test-tokenizer-0-gpt-2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;38;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;123;llama_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-llama-bpe "/home/josh/llama.cpp-master/bin/test-tokenizer-0" "/home/josh/llama.cpp-master/models/ggml-vocab-llama-bpe.gguf")
set_tests_properties(test-tokenizer-0-llama-bpe PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;38;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;124;llama_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-llama-spm "/home/josh/llama.cpp-master/bin/test-tokenizer-0" "/home/josh/llama.cpp-master/models/ggml-vocab-llama-spm.gguf")
set_tests_properties(test-tokenizer-0-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;38;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;125;llama_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-mpt "/home/josh/llama.cpp-master/bin/test-tokenizer-0" "/home/josh/llama.cpp-master/models/ggml-vocab-mpt.gguf")
set_tests_properties(test-tokenizer-0-mpt PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;38;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;126;llama_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-phi-3 "/home/josh/llama.cpp-master/bin/test-tokenizer-0" "/home/josh/llama.cpp-master/models/ggml-vocab-phi-3.gguf")
set_tests_properties(test-tokenizer-0-phi-3 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;38;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;127;llama_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-qwen2 "/home/josh/llama.cpp-master/bin/test-tokenizer-0" "/home/josh/llama.cpp-master/models/ggml-vocab-qwen2.gguf")
set_tests_properties(test-tokenizer-0-qwen2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;38;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;128;llama_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-refact "/home/josh/llama.cpp-master/bin/test-tokenizer-0" "/home/josh/llama.cpp-master/models/ggml-vocab-refact.gguf")
set_tests_properties(test-tokenizer-0-refact PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;38;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;129;llama_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-0-starcoder "/home/josh/llama.cpp-master/bin/test-tokenizer-0" "/home/josh/llama.cpp-master/models/ggml-vocab-starcoder.gguf")
set_tests_properties(test-tokenizer-0-starcoder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;38;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;130;llama_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-tokenizers-ggml-vocabs "/home/josh/llama.cpp-master/tests/test-tokenizers-repo.sh" "https://huggingface.co/ggml-org/vocabs" "/home/josh/llama.cpp-master/models/ggml-vocabs")
set_tests_properties(test-tokenizers-ggml-vocabs PROPERTIES  LABELS "main" WORKING_DIRECTORY "/home/josh/llama.cpp-master/bin" _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;66;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;133;llama_test_cmd;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-sampling "/home/josh/llama.cpp-master/bin/test-sampling")
set_tests_properties(test-sampling PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;147;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-grammar-parser "/home/josh/llama.cpp-master/bin/test-grammar-parser")
set_tests_properties(test-grammar-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;148;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-grammar-integration "/home/josh/llama.cpp-master/bin/test-grammar-integration")
set_tests_properties(test-grammar-integration PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;149;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-llama-grammar "/home/josh/llama.cpp-master/bin/test-llama-grammar")
set_tests_properties(test-llama-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;150;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-chat "/home/josh/llama.cpp-master/bin/test-chat")
set_tests_properties(test-chat PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;151;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-json-schema-to-grammar "/home/josh/llama.cpp-master/bin/test-json-schema-to-grammar")
set_tests_properties(test-json-schema-to-grammar PROPERTIES  LABELS "main" WORKING_DIRECTORY "/home/josh/llama.cpp-master" _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;154;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-tokenizer-1-llama-spm "/home/josh/llama.cpp-master/bin/test-tokenizer-1-spm" "/home/josh/llama.cpp-master/models/ggml-vocab-llama-spm.gguf")
set_tests_properties(test-tokenizer-1-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;38;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;180;llama_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-chat-parser "/home/josh/llama.cpp-master/bin/test-chat-parser")
set_tests_properties(test-chat-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;186;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-chat-peg-parser "/home/josh/llama.cpp-master/bin/test-chat-peg-parser")
set_tests_properties(test-chat-peg-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;187;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-chat-template "/home/josh/llama.cpp-master/bin/test-chat-template")
set_tests_properties(test-chat-template PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;188;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-json-partial "/home/josh/llama.cpp-master/bin/test-json-partial")
set_tests_properties(test-json-partial PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;189;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-log "/home/josh/llama.cpp-master/bin/test-log")
set_tests_properties(test-log PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;190;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-peg-parser "/home/josh/llama.cpp-master/bin/test-peg-parser")
set_tests_properties(test-peg-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;191;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-regex-partial "/home/josh/llama.cpp-master/bin/test-regex-partial")
set_tests_properties(test-regex-partial PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;202;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-thread-safety "/home/josh/llama.cpp-master/bin/test-thread-safety" "-hf" "ggml-org/models" "-hff" "tinyllamas/stories15M-q4_0.gguf" "-ngl" "99" "-p" "The meaning of life is" "-n" "128" "-c" "256" "-ub" "32" "-np" "4" "-t" "2")
set_tests_properties(test-thread-safety PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;205;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-arg-parser "/home/josh/llama.cpp-master/bin/test-arg-parser")
set_tests_properties(test-arg-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;212;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-opt "/home/josh/llama.cpp-master/bin/test-opt")
set_tests_properties(test-opt PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;217;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-gguf "/home/josh/llama.cpp-master/bin/test-gguf")
set_tests_properties(test-gguf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;219;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-backend-ops "/home/josh/llama.cpp-master/bin/test-backend-ops")
set_tests_properties(test-backend-ops PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;220;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-model-load-cancel "/home/josh/llama.cpp-master/bin/test-model-load-cancel")
set_tests_properties(test-model-load-cancel PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;222;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-autorelease "/home/josh/llama.cpp-master/bin/test-autorelease")
set_tests_properties(test-autorelease PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;223;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-barrier "/home/josh/llama.cpp-master/bin/test-barrier")
set_tests_properties(test-barrier PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;227;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-quantize-fns "/home/josh/llama.cpp-master/bin/test-quantize-fns")
set_tests_properties(test-quantize-fns PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;228;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-quantize-perf "/home/josh/llama.cpp-master/bin/test-quantize-perf")
set_tests_properties(test-quantize-perf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;229;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-rope "/home/josh/llama.cpp-master/bin/test-rope")
set_tests_properties(test-rope PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;230;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-mtmd-c-api "/home/josh/llama.cpp-master/bin/test-mtmd-c-api")
set_tests_properties(test-mtmd-c-api PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;235;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
add_test(test-alloc "/home/josh/llama.cpp-master/bin/test-alloc")
set_tests_properties(test-alloc PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/josh/llama.cpp-master/tests/CMakeLists.txt;106;add_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;243;llama_build_and_test;/home/josh/llama.cpp-master/tests/CMakeLists.txt;0;")
