/* This file was generated by configure. */
#define TARGET "x86_64-unknown-freebsd14.3"
#define x86_64 1
#define INCLUDE_PATHS "/usr/local/lib/lacc/include", "/usr/local/include", "/usr/include"
#define LIB_PATH "/usr/local/lib/lacc"
