# crawler configuration file

seed_url = https://usa.gov
threads = 6
max_depth = 16
polite_delay = 0
sitemap_discovery = true
malicious_file = malicious.txt
user_agent = custom-crawler
db_file = crawler.db
