#ifndef QTCCLONE2_GLOBAL_H
#define QTCCLONE2_GLOBAL_H

#if defined(QTCCLONE2_LIBRARY)
#  define QTCCLONE2_EXPORT Q_DECL_EXPORT
#else
#  define QTCCLONE2_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCCLONE2_GLOBAL_H
