/* output generated by jas.c (table-driven prototype) */

    .section
    .data msg
    .quad 0, 0, 0
size:
    .quad 0
    .section
    .text
    .global _start
_start:
    movq 1, %rax /* id: 1 */
movq msg, %rdi
    lea 8(%rsp,%,1), %rbx /* id: 11 */
    pushq 10 /* id: 12 */
popq %rcx
    addq %rdi, %rax /* id: 20 */
    subq 5, %rcx /* id: 23 */
    imulq %rbx, %rax /* id: 28 */
    cmpq 100, %rax /* id: 41 */
    jg label_exit /* id: 47 */
label_loop:
incq %rbx
    pushq %rbx /* id: 13 */
popq %rax
    jmp label_loop /* id: 43 */
label_exit:
syscall ret
